# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
      - name: npm install and build webpack  
        run: |
          npm install
          npm run build
    
  test:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-latest, windows-2016]
  
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install and test
      run: |
        npm install
        npm test -- -u
      env:
        CI: true
